### ISSUE TITLE
Upstream flashbang on solaris ridge

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [RMC-14/RMC-14#6362]
## Description
I have no clue where it is, but someone used it during a round and my eyes and ears are gone, send help

**Comment by SirChopwood** [comment]
Can confirm its on the map. 
```yml
- proto: GrenadeFlashBang
  entities:
  - uid: 39108
    components:
    - type: Transform
      pos: 101.59375,-38.71875
      parent: 1
```
@DrSmugleaf do we want this swapped to an RMC version or just remove to prevent abuse?
